# הגדרת החיבור לבסיס הנתונים החזותי בזיכרון (H2)
spring.datasource.url=jdbc:h2:mem:bankdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# הפעלת ממשק הניהול בדפדפן (כדי שתוכלו לראות את הטבלאות שלכן)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# הגדרות שיוצרות ומעדכנות את הטבלאות באופן אוטומטי לפי המחלקות שנכתוב ב-Java
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true